DEFAULT_CARD_HEIGHT = 600
DEFAULT_CARD_WIDTH = 400

DEFAULT_TITLE_FONT = "msyh.ttc"
DEFAULT_INFO_FONT = "msyh.ttc"
DEFAULT_STATS_FONT = "msyh.ttc"
DEFAULT_TITLE_SIZE = 24
DEFAULT_INFO_SIZE = 18
DEFAULT_STATS_SIZE = 16
