CARD_HEIGHT = 'CARD_HEIGHT'
CARD_WIDTH = 'CARD_WIDTH'

TITLE_FONT = 'TITLE_FONT'
INFO_FONT = 'INFO_FONT'
STATS_FONT = 'STATS_FONT'
TITLE_SIZE = 'TITLE_SIZE'
INFO_SIZE = 'INFO_SIZE'
STATS_SIZE = 'STATS_SIZE'
